# Generated by Django 5.1.3 on 2025-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('tktno', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('f_station', models.CharField(max_length=20)),
                ('to_station', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrocard',
            fields=[
                ('card_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('expiry', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metrostations',
            fields=[
                ('stid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='metroticket_bookinghistory',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_station', models.CharField(max_length=20)),
                ('t_station', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
